export const MAIN_SET_MESSAGE    = 'MAIN_SET_MESSAGE'
export const MAIN_SET_FETCHING   = 'MAIN_SET_FETCHING'

export const CATEGORIES_SET_DATA = 'CATEGORIES_SET_DATA'
export const NOTES_SET_DATA      = 'NOTES_SET_DATA'
